classdef W_Analysis < ...
        W_Analysis_Average & ...
        W_Analysis_Bin & ...
        W_Analysis_CellMath & ...
        W_Analysis_Cond & ...
        W_Analysis_Consecutives & ...
        W_Analysis_Cycle & ...
        W_Analysis_Misc & ...
        W_Analysis_Rand & ...
        W_Analysis_Table_Advanced_Selection & ...
        W_Analysis_Table_Advanced_Computation & ...
        W_Analysis_Table_Advanced_Format & ...
        W_Analysis_Stats & ...
        W_Analysis_DimensionalityReduction & ...
        W_Analysis_Distance
end