looper = S_looper_folder('../../Data/');
jobs = S_jobs();
jobs.set_loopers({'folder'}, {looper});
jobs.power_off;
jobs.add_jobs_with_looper_folder([], 'event2trials', ...
    {'events'}, {'inputname1'}, 'trials');
jobs.add_jobs_with_looper_folder([], 'preprocess_trials', ...
    {'trials'}, {}, 'games');
%% epoch cue -600 to 1100
jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_by_marker', ...
    {'spikes', 'trials'}, {1199, 1, -600:10:1100, 100}, 'epoch_cueon_600_1000');
jobs.add_jobs_with_looper_folder([], 'W.select_trials', ...
    {'epoch_cueon_600_1000','games'},  {}, ...
    {'EPOCH_final','GAMES_final'});
%% epoch cue spike trains
jobs.add_jobs_with_looper_folder([], 'W.epoch_spiketrains_by_marker', ...
    {'spikes', 'trials'}, {1199, 1, -600, 1100, 1}, 'epoch_st_cueon_600_1000');
jobs.add_jobs_with_looper_folder([], 'W.select_trials', ...
    {'epoch_st_cueon_600_1000','games'},  {}, ...
    {'EPOCH_ST_final'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
    {'EPOCH_ST_final', 'GAMES_final'}, {}, 'spiketrains');
%% shuffle
jobs.add_jobs_with_looper_folder([], 'function_shuffle', ...
    {'EPOCH_ST_final'},  {}, ...
    {'EPOCH_ST_final_shuffled'}); 
% jobs.power_on;
jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_from_spiketrains', ...
    {'EPOCH_ST_final_shuffled'},  {-600:10:1100, 100}, ...
    {'EPOCH_final_shuffled'}); 
%% shuffle
% jobs.add_jobs_with_looper_folder([], 'function_shuffle_rate', ...
%     {'EPOCH_ST_final','GAMES_final'},  {}, ...
%     {'EPOCH_ST_final_shuffled_rate'}); 
% jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_from_spiketrains', ...
%     {'EPOCH_ST_final_shuffled_rate'},  {-600:10:1100, 100}, ...
%     {'EPOCH_final_shuffled_rate'}); 
% jobs.power_on;
jobs.add_jobs_with_looper_folder([], 'function_shuffle_rate', ...
    {'EPOCH_final'},  {}, ...
    {'EPOCH_final_shuffled_rate'}); 

% jobs.power_off;
jobs.add_jobs_with_looper_folder([], 'function_filter0', ...
    {'EPOCH_final'}, {}, ...
    {'EPOCH_final_non0'});

jobs.add_jobs_with_looper_folder([], 'function_shuffle_trial', ...
    {'EPOCH_ST_final'},  {}, ...
    {'EPOCH_ST_final_shuffled_trial'}); 
jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_from_spiketrains', ...
    {'EPOCH_ST_final_shuffled_trial'},  {-600:10:1100, 100}, ...
    {'EPOCH_final_shuffled_trial'}); 
%% epoch cue 75 to 750
jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_by_marker', ...
    {'spikes', 'trials'}, {1199, 1, 412.5, 675, 'filter_appearance', 1}, 'epoch_cueon_75_750');
jobs.add_jobs_with_looper_folder([], 'W.select_trials', ...
    {'epoch_cueon_75_750','games'},  {}, ...
    {'EPOCH_final_75_750'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
    {'EPOCH_final_75_750', 'GAMES_final'}, {}, 'epoch_75_750');
%% epoch go -600 to 1100
jobs.power_on;
jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_by_marker', ...
    {'spikes', 'trials'}, {[1038 1121], 1, -600:10:1100, 100}, 'epoch_go_600_1100');

jobs.add_jobs_with_looper_folder([], 'W.select_trials', ...
    {'epoch_go_600_1100','games'},  {}, ...
    {'EPOCH_final_go','GAMES_final_go'});
jobs.add_jobs_with_looper_folder([], 'W.epoch_spiketrains_by_marker', ...
    {'spikes', 'trials'}, {[1038 1121], 1, -600, 1100, 1}, 'epoch_st_go_600_1000');

jobs.add_jobs_with_looper_folder([], 'W.select_trials', ...
    {'epoch_st_go_600_1000','games'},  {}, ...
    {'EPOCH_GOfinal_600_1100', 'GAMES_finalGO'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
    {'EPOCH_GOfinal_600_1100', 'GAMES_finalGO'}, {}, 'spiketrains_GO');
jobs.parfor_off;
jobs.overwrite_on;
jobs.run()