looper = S_looper_folder('../../Data/');
jobs = S_jobs();
jobs.set_loopers({'folder'}, {looper});
jobs.add_jobs_with_looper_folder([], 'event2trials', ...
    {'events'}, {'inputname1'}, 'trials');
jobs.add_jobs_with_looper_folder([], 'preprocess_trials', ...
    {'trials'}, {}, 'games');
%% cue period
% epoch cue -600 to 1100
jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_by_marker', ...
    {'spikes', 'trials'}, {1199, 1, -600:10:1100, 100}, 'epoch_cueon_600_1000');
jobs.add_jobs_with_looper_folder([], 'W.select_trials', ...
    {'epoch_cueon_600_1000','games'},  {}, ...
    {'EPOCH_cue','games_cue'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
    {'EPOCH_cue', 'games_cue'}, {}, 'cue_all');
% epoch cue spike trains
jobs.add_jobs_with_looper_folder([], 'W.epoch_spiketrains_by_marker', ...
    {'spikes', 'trials'}, {1199, 1, -600, 1100, 1}, 'epoch_st_cueon_600_1000');
jobs.add_jobs_with_looper_folder([], 'W.select_trials', ...
    {'epoch_st_cueon_600_1000','games'},  {}, ...
    {'ST_cue'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
    {'ST_cue', 'games_cue'}, {}, 'ST_cue_all');
%% go period
jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_by_marker', ...
    {'spikes', 'trials'}, {[1038 1121], 1, -600:10:1100, 100}, 'epoch_go_600_1100');
jobs.add_jobs_with_looper_folder([], 'W.select_trials', ...
    {'epoch_go_600_1100','games'},  {}, ...
    {'EPOCH_go','games_go'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
    {'EPOCH_go', 'games_go'}, {}, 'go_all');
jobs.add_jobs_with_looper_folder([], 'W.epoch_spiketrains_by_marker', ...
    {'spikes', 'trials'}, {[1038 1121], 1, -600, 1100, 1}, 'epoch_st_go_600_1000');
jobs.add_jobs_with_looper_folder([], 'W.select_trials', ...
    {'epoch_st_go_600_1000','games'},  {}, ...
    {'ST_go'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
    {'ST_go', 'games_go'}, {}, 'ST_go_all');
%% epoch cue 75 to 750
% jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_by_marker', ...
%     {'spikes', 'trials'}, {1199, 1, 412.5, 675, 'filter_appearance', 1}, 'epoch_cueon_75_750');
% jobs.add_jobs_with_looper_folder([], 'W.select_trials', ...
%     {'epoch_cueon_75_750','games'},  {}, ...
%     {'EPOCH_complete_75_750'});
% jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
%     {'EPOCH_complete_75_750', 'GAMES_complete'}, {}, 'epoch_75_750');
% %% shuffle
% jobs.add_jobs_with_looper_folder([], 'function_shuffle', ...
%     {'EPOCH_ST_complete'},  {}, ...
%     {'EPOCH_ST_complete_shuffled'}); 
% % jobs.power_on;
% jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_from_spiketrains', ...
%     {'EPOCH_ST_complete_shuffled'},  {-600:10:1100, 100}, ...
%     {'EPOCH_complete_shuffled'}); 
% %% shuffle
% % jobs.add_jobs_with_looper_folder([], 'function_shuffle_rate', ...
% %     {'EPOCH_ST_complete','GAMES_complete'},  {}, ...
% %     {'EPOCH_ST_complete_shuffled_rate'}); 
% % jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_from_spiketrains', ...
% %     {'EPOCH_ST_complete_shuffled_rate'},  {-600:10:1100, 100}, ...
% %     {'EPOCH_complete_shuffled_rate'}); 
% % jobs.power_on;
% jobs.add_jobs_with_looper_folder([], 'function_shuffle_rate', ...
%     {'EPOCH_complete'},  {}, ...
%     {'EPOCH_complete_shuffled_rate'}); 
% 
% % jobs.power_off;
% jobs.add_jobs_with_looper_folder([], 'function_filter0', ...
%     {'EPOCH_complete'}, {}, ...
%     {'EPOCH_complete_non0'});
% 
% jobs.add_jobs_with_looper_folder([], 'function_shuffle_trial', ...
%     {'EPOCH_ST_complete'},  {}, ...
%     {'EPOCH_ST_complete_shuffled_trial'}); 
% jobs.add_jobs_with_looper_folder([], 'W.epoch_spikebinning_from_spiketrains', ...
%     {'EPOCH_ST_complete_shuffled_trial'},  {-600:10:1100, 100}, ...
%     {'EPOCH_complete_shuffled_trial'}); 
jobs.parfor_off;
jobs.overwrite_off;
jobs.run()