looper = S_looper_folder('../Data/');
jobs = S_jobs();
jobs.set_loopers({'folder'}, {looper});
jobs.power_off;
%% shuffled
% jobs.power_on;
infiles = {'EPOCH_sigcells', 'EPOCH_nonsigcells', 'EPOCH_sigcells_shuffled', ...
    'EPOCH_sigcells_shuffled_rate', 'EPOCH_sigcells_shuffled_trial', ...
    'EPOCH_sigcells_final_non0'};
outfiles = {'anova_nochocie', 'anova_nochocie_nonsig', 'anova_nochocie_shuffled', ...
    'anova_nochocie_shuffled_rate', 'anova_nochocie_shuffled_trial', ...
    'anova_nochocie_non0'};
outfilesall = {'anova_nochocie_allcells', 'anova_nochocie_allcells_nonsig', 'anova_nochocie_shuffled_allcells', ...
    'anova_nochocie_shuffled_rate_allcells', 'anova_nochocie_shuffled_trial_allcells', ...
    'anova_nochocie_non0_allcells'};
for i = 1:length(infiles)
    %% anova no choice
    factornames = {'drop', 'delay'};
    jobs.add_jobs_with_looper_folder([], 'W.anovan_slidingwindow', ...
        {infiles{i}, 'GAMES_final'}, ...
        {factornames, 'model', 'interaction','window_significance', [75 750]}, ...
        {outfiles{i}});
    jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells', ...
        {outfiles{i}}, {}, outfilesall{i});
    %% anova with choice
    factornames = {'drop', 'delay', 'choice'};
    model = [1,0,0;0,1,0;1,1,0;0,0,1];
    jobs.add_jobs_with_looper_folder([], 'W.anovan_slidingwindow', ...
        {infiles{i}, 'GAMES_final'}, ...
        {factornames, 'model', model,'window_significance', [75 750]}, ...
        {replace(outfiles{i}, 'nochocie', 'choice')});
    jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells', ...
        {replace(outfiles{i}, 'nochocie', 'choice')}, {}, replace(outfilesall{i}, 'nochocie', 'choice'));
end
jobs.power_off;
%% anova at go
% jobs.power_on;
factornames = {'drop', 'delay', 'choice', 'release1', 'cue1'};
model = [1,0,0,0,0; ...
         0,1,0,0,0; ...
         1,1,0,0,0; ...
         0,0,1,0,0; ...
         0,0,0,1,0; ...
         0,0,0,0,1];
jobs.add_jobs_with_looper_folder([], 'W.anovan_slidingwindow', ...
    {'EPOCH_GOfinal_600_1100', 'GAMES_final'}, ...
    {factornames, 'model', model}, ...
    {'anova_go'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells', ...
    {'anova_go'}, {}, 'anova_go_allcells');
% jobs.power_off;
%% behavioral modeling of value
modelnames = ["base", "YP"];
for i = 1:1 % 2
    jobs.add_jobs_with_looper_folder([], 'function_model', ...
        {'GAMES_final'}, {i}, {sprintf('result_RL_%s', modelnames(i))});
end
results = W.str2cell(strcat('result_RL_', modelnames));
jobs.add_jobs_with_looper_folder([], 'W.struct_combine', ...
    results, {}, {'result_RL'});
jobs.add_jobs_with_looper_folder([], 'function_value', ...
    {'GAMES_final', 'result_RL'}, {'model_base'}, ...
    {'GAMES_value'});
%% anova with value
factornames = {'drop', 'delay', 'DV'};
jobs.add_jobs_with_looper_folder([], 'W.anovan_slidingwindow', ...
    {'EPOCH_sigcells', 'GAMES_value'}, ...
    {factornames, 'window_significance', [75 750], 'continuous', [1 2 3]}, ...
    {'anova_value_cont'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells', ...
    {'anova_value_cont'}, {}, 'anova_value_cont_allcells');

factornames = {'drop', 'delay', 'DV'};
jobs.add_jobs_with_looper_folder([], 'W.anovan_slidingwindow', ...
    {'EPOCH_sigcells', 'GAMES_value'}, ...
    {factornames, 'window_significance', [75 750], 'continuous', [1 2 3], 'is_normalize', true}, ...
    {'anova_value_cont_normalized'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells', ...
    {'anova_value_cont_normalized'}, {}, 'anova_value_cont_allcells_normalized');


% factornames = {'drop', 'delay', 'DV'};
% model = [1 0 0;0 1 0; 0 0 1];
% jobs.add_jobs_with_looper_folder([], 'W.anovan_slidingwindow', ...
%     {'EPOCH_sigcells', 'GAMES_value'}, ...
%     {factornames, 'window_significance', [75 750], 'model', model, 'continuous', [3]}, ...
%     {'anova_value'});
% jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells', ...
%     {'anova_value'}, {}, 'anova_value_allcells');
%% mean trajectory by yellow/purple

% jobs.power_on;
factornames = {'drop', 'delay', 'DV'};
jobs.add_jobs_with_looper_folder([], 'W.anovan_slidingwindow', ...
    {'EPOCH_final', 'GAMES_value'}, ...
    {factornames, 'continuous', [1 2 3]}, ...
    {'anova_value_cont_nonsigcells_included'});

jobs.add_jobs_with_looper_folder([], 'func_traj', ...
    {'EPOCH_GOfinal_600_1100', 'GAMES_final', 'anova_value_cont_nonsigcells_included'}, ...
    {}, ...
    {'traj_go'});



jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells', ...
    {'traj_go'}, {}, 'traj_go_allcells');

jobs.add_jobs_with_looper_folder([], 'func_traj2', ...
    {'EPOCH_GOfinal_600_1100', 'GAMES_final', 'anova_value_cont_nonsigcells_included'}, ...
    {}, ...
    {'traj_go2'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells', ...
    {'traj_go2'}, {}, 'traj_go2_allcells');
jobs.power_on;

jobs.add_jobs_with_looper_folder([], 'func_traj3', ...
    {'EPOCH_GOfinal_600_1100', 'GAMES_final', 'anova_value_cont_nonsigcells_included'}, ...
    {}, ...
    {'traj_go3'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells', ...
    {'traj_go3'}, {}, 'traj_go3_allcells');

jobs.parfor_off;
jobs.overwrite_on;
jobs.run()
% %% process go anova
% anv = looper.looper_loadmix('anova_go_allcells');
% anv = W.decell(anv);
% anv = W.anovan_mergefactors(anv, {'release1'}, {'motor'});
% anv = W.anovan_mergefactors(anv, {'delay', 'drop', 'drop*delay'}, {'drop|delay'});
% looper.looper_save_master(anv, 'anova_go_allcells_formatted');

