%%
plt = SW_plt_from_yml('fig.yml');
plt.plt_switch.addABCs = false;
looper = S_looper_folder('../Data', '');
jobs = S_jobs();
jobs.set_loopers({'folder'}, {looper});
jobs.plotmode_on(plt);

jobs.add_jobs_with_looper_folder({'all', 'all'}, 'SW_fig', ...
    {'anova_value_cont_allcells_normalized'}, ...
    {'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 1, ...
     'varargin_axes', {'plottype', 'shade', 'color', {'AZcactus', 'AZsky', 'AZsand', 'magenta'}, ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.03 0.5], 'ytick', -1:.2:1}, ...
        {'plottype', 'shade', 'color', {'AZcactus', 'AZsky', 'AZsand', 'magenta'}, ...
            'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.015], 'ytick', -0.05:0.01:0.05}, ...
     'ABC_axes', '  '}, ...
    {'anova_cue'});


jobs.add_jobs_with_looper_folder({'all', 'all'}, 'SW_fig', ...
    {'anova_GOvalue_cont_allcells_normalized'}, ...
    {'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 1, ...
     'varargin_axes', {'plottype', 'shade', 'color', {'AZcactus', 'AZsky', 'AZsand', 'magenta'}, ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.03 0.5], 'ytick', -1:.2:1}, ...
        {'plottype', 'shade', 'color', {'AZcactus', 'AZsky', 'AZsand', 'magenta'}, ...
            'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.015], 'ytick', -0.05:0.01:0.05}, ...
     'ABC_axes', '  '}, ...
    {'anova_GO'});

jobs.parfor_off;
jobs.overwrite_on;
jobs.run()