classdef W_Neuro < W_Neuro_Import & ...
        W_Neuro_Event & ...
        W_Neuro_Epoch & ...
        W_Neuro_Format & ...
        W_Neuro_Looper & ...
        W_Neuro_ANOVA & ...
        W_Neuro_Select & ...
        W_Neuro_1D_EnergyLandscape & ...
        W_Neuro_1D_LinearDynamics & ...
        W_Neuro_Trajectory & ...
        W_Neuro_Decoding & ...
		W_Neuro_Dimensionality_Reduction
end