function out = function_preprocess_neuro(data)
%     factornames = {'choice', 'drop', 'delay', 'release1'};
%     model = [1,0,0,0; ...
%         0,1,0,0; ...
%         0,0,1,0; ...
%         0,1,1,0; ...
%         0,0,0,1];
    factornames = {'drop', 'delay'};
    model = [1,0;0,1;1,1];
    spikes = rmfield(data, {'epochs', 'games', 'spikeID', 'animal'});
    spikes.spikes = data.epochs;
    spikes.info_spikes = W.struct_sub(data, {'spikeID', 'animal'});
    out = W.filter_cells_master(spikes, data.games, ...
        'ANOVA', {factornames, 'window_significance', [75 750], 'model', model});
    out.games = data.games;
end