data = W.load('../Data/data_epoched_cue_RF.mat');
%%
factornames = {'drop', 'delay'};
model = [1,0;0,1;1,1];
out = W.neuro_ANOVA_slidingwindow_mergedsessions(data.epochs, data.games, ...
    data.idx_game, factornames, ...
    'window_significance', [0 1000], 'model', model);
W.save('../Results/anova_cue_nochoice.mat', 'anova', out);
%%
factornames = {'choice', 'drop', 'delay'};
model = [1,0,0;0,1,0;0,0,1;0,1,1];
out = W.neuro_ANOVA_slidingwindow_mergedsessions(data.epochs, data.games, ...
    data.idx_game, factornames, ...
    'window_significance', [0 1000], 'model', model);
W.save('../Results/anova_cue_choice.mat', 'anova', out);
%%
factornames = {'choice', 'drop', 'delay', 'release1'};
model = [1,0,0,0; ...
              0,1,0,0; ...
              0,0,1,0; ...
              0,1,1,0; ...
              0,0,0,1];
out = W.neuro_ANOVA_slidingwindow_mergedsessions(data.epochs, data.games, ...
    data.idx_game, factornames, ...
    'window_significance', [0 1000], 'model', model);
W.save('../Results/anova_cue_action.mat', 'anova', out);
%%
data = W.load('../Data/data_epoched_go_RF.mat');
%%
factornames = {'drop', 'delay'};
model = [1,0;0,1;1,1];
out = W.neuro_ANOVA_slidingwindow_mergedsessions(data.epochs, data.games, ...
    data.idx_game, factornames, ...
    'window_significance', [0 1000], 'model', model);
W.save('../Results/anova_go_nochoice.mat', 'anova', out);
%%
factornames = {'choice', 'drop', 'delay'};
model = [1,0,0;0,1,0;0,0,1;0,1,1];
out = W.neuro_ANOVA_slidingwindow_mergedsessions(data.epochs, data.games, ...
    data.idx_game, factornames, ...
    'window_significance', [0 1000], 'model', model);
W.save('../Results/anova_go_choice.mat', 'anova', out);
%%
factornames = {'choice', 'drop', 'delay', 'release1'};
model = [1,0,0,0; ...
              0,1,0,0; ...
              0,0,1,0; ...
              0,1,1,0; ...
              0,0,0,1];
out = W.neuro_ANOVA_slidingwindow_mergedsessions(data.epochs, data.games, ...
    data.idx_game, factornames, ...
    'window_significance', [0 1000], 'model', model);
W.save('../Results/anova_go_action.mat', 'anova', out);
%%
plt = W_plt;
plt.figure;
xs = -600:10:1100;
plt.plot(xs,out.perc_significant, [], 'line');
plt.setfig_ax('xlabel', 'time', 'ylabel', 'p(significant neurons)', ...
    'legend', out.name_factors, 'xlim', [-500 1000], 'legloc', 'NW');
plt.update