data = W.load('../../TempData/data');
go = data.go;
go{3} = W.format_combinecells(go);
timeat = go{1}.time_at;
ntime = length(timeat);
plt = SW_plt_from_yml('../fig.yml');
%% go period
% %% ANOVA: drop + delay + interaction + yellow/purple + motor + choice
% factornames = {'drop', 'delay', 'choice', 'motor', 'GO cue'};
% factornames_in_data = {'drop', 'delay', 'choice', 'release1', 'cue1'};
% model = [1,0,0,0,0; ...
%          0,1,0,0,0; ...
%          1,1,0,0,0; ...
%          0,0,1,0,0; ...
%          0,0,0,1,0; ...
%          0,0,0,0,1];
% anv = {};
% for i = 1:2
%     d = go{i};
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
%     % merge factors
%     anv{i} = W.anovan_mergefactors(anv{i}, {'delay', 'drop', 'drop*delay'}, {'drop|delay'});
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_all_factors', 'anv', anv);
% %% Figure - ANOVA
% anv = W.load('../../TempData/result/anvGO_all_factors');
% SW_fig(plt, anv{1}, anv{2}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
%     'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
%      'data_axes', 1, 2, 1, 2, ...
%      'varargin_axes', {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      'ABC_axes', 'ABCD', 'nx', 2, 'ny', 2, ...
%      'varargin_fig', 'is_title', 'all', 'savename', 'anvGO_all_factors');
% 
% 
% %% improve yellow/purple by selecting only behavioral conditions where it matters
% factornames = {'drop', 'delay', 'choice', 'motor', 'GO cue'};
% factornames_in_data = {'drop', 'delay', 'choice', 'release1', 'cue1'};
% model = [1,0,0,0,0; ...
%          0,1,0,0,0; ...
%          1,1,0,0,0; ...
%          0,0,1,0,0; ...
%          0,0,0,1,0; ...
%          0,0,0,0,1];
% anv = {};
% ps = W.load('../../TempData/behavior_pYP');
% for i = 1:2
%     d = go{i};
%     idYP = find(ps(i,:) * 9 < 0.05);
%     for gi = 1:length(d.games)
%         g = d.games{gi};
%         g.cue1(~ismember(g.condition, idYP)) = "other";
%         d.games{gi} = g;
%     end
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
%     % merge factors
%     anv{i} = W.anovan_mergefactors(anv{i}, {'delay', 'drop', 'drop*delay'}, {'drop|delay'});
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_YP_other', 'anv', anv);
% %% v2
% factornames = {'drop', 'delay', 'choice', 'motor', 'GO cue'};
% factornames_in_data = {'drop', 'delay', 'choice', 'release1', 'cue1'};
% model = [1,0,0,0,0; ...
%          0,1,0,0,0; ...
%          1,1,0,0,0; ...
%          0,0,1,0,0; ...
%          0,0,0,1,0; ...
%          0,0,0,0,1];
% anv = {};
% ps = W.load('../../TempData/behavior_pYP');
% for i = 1:2
%     d = go{i};
%     idYP = find(ps(i,:) * 9 < 0.05);
%     for gi = 1:length(d.games)
%         g = d.games{gi};
%         g.cue1(ismember(g.condition, idYP)) = "other";
%         d.games{gi} = g;
%     end
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
%     % merge factors
%     anv{i} = W.anovan_mergefactors(anv{i}, {'delay', 'drop', 'drop*delay'}, {'drop|delay'});
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_YP_opposite', 'anv', anv);
% %% control
% factornames = {'drop', 'delay', 'choice', 'motor', 'GO cue'};
% factornames_in_data = {'drop', 'delay', 'choice', 'release1', 'cue1'};
% model = [1,0,0,0,0; ...
%          0,1,0,0,0; ...
%          1,1,0,0,0; ...
%          0,0,1,0,0; ...
%          0,0,0,1,0; ...
%          0,0,0,0,1];
% anv = {};
% ps = W.load('../../TempData/behavior_pYP');
% for i = 1:2
%     d = go{i};
%     idYP = find(ps(i,:) * 9 < 0.05);
%     for gi = 1:length(d.games)
%         g = d.games{gi};
%         g.cue1(ismember(g.condition, idYP)) = "main";
%         g.cue1(~ismember(g.condition, idYP)) = "other";
%         d.games{gi} = g;
%     end
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
%     % merge factors
%     anv{i} = W.anovan_mergefactors(anv{i}, {'delay', 'drop', 'drop*delay'}, {'drop|delay'});
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_YP_control', 'anv', anv);
% %%
% anv = W.load('../../TempData/result/anvGO_YP_other')
% anv = W.load('../../TempData/result/anvGO_YP_opposite')
% SW_fig(plt, anv{1}, anv{2}, anv{3}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
%     'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
%      'data_axes', 1, 2, 3, 1, 2, 3, ...
%      'varargin_axes', {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', ''}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      'ABC_axes', 'ABACDB', 'nx', 2, 'ny', 3, ...
%      'varargin_fig', 'is_title', 'all');



%% ANOVA: condition 
factornames = {'condition', 'motor', 'GO cue', 'choice'};
factornames_in_data = {'condition', 'release1', 'cue1', 'choice'};
nested = zeros(4,4);
nested(3,1) = 1;
anv = {};
for i = 1:2
    d = go{i};
    anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
        'factornames_in_data', factornames_in_data, ...
        'nested', nested);
end
anv{3} = W.format_combinecells(anv);
W.save('../../TempData/result/anvGO_condition', 'anv', anv);
%%
anv = W.load('../../TempData/result/anvGO_condition');
SW_fig(plt, anv{1}, anv{2}, anv{3}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
    'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 2, 3, 1, 2, 3, ...
     'varargin_axes', {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
     {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', ''}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     {'plottype', 'shade', ...
     'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     'ABC_axes', 'ABACDB', 'nx', 2, 'ny', 3, ...
     'varargin_fig', 'is_title', 'all', 'savename', 'anova_GO');
% %% improve yellow/purple by selecting only behavioral conditions where it matters
% factornames = {'condition', 'motor', 'GO cue'};
% factornames_in_data = {'condition', 'release1', 'cue1'};
% model = [1,0,0; ...
%          0,1,0; ...
%          0,0,1];
% anv = {};
% ps = W.load('../../TempData/behavior_pYP');
% for i = 1:2
%     d = go{i};
%     idYP = find(ps(i,:) * 9 < 0.05);
%     for gi = 1:length(d.games)
%         g = d.games{gi};
%         g.cue1(~ismember(g.condition, idYP)) = "other";
%         d.games{gi} = g;
%     end
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_YP_other', 'anv', anv);
% %% v2
% factornames = {'condition', 'motor', 'GO cue'};
% factornames_in_data = {'condition', 'release1', 'cue1'};
% model = [1,0,0; ...
%          0,1,0; ...
%          0,0,1];
% anv = {};
% ps = W.load('../../TempData/behavior_pYP');
% for i = 1:2
%     d = go{i};
%     idYP = find(ps(i,:) * 9 < 0.05);
%     for gi = 1:length(d.games)
%         g = d.games{gi};
%         g.cue1(ismember(g.condition, idYP)) = "other";
%         d.games{gi} = g;
%     end
%     anv{i} = W.anovan_slidingwindow_combinedgames(d, factornames, ...
%         'factornames_in_data', factornames_in_data, ...
%         'model', model);
% end
% anv{3} = W.format_combinecells(anv);
% W.save('../../TempData/result/anvGO_YP_opposite', 'anv', anv);
% %%
% anv = W.load('../../TempData/result/anvGO_YP');
% SW_fig(plt, anv{1}, anv{2}, anv{3}, 'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA', ...
%     'ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega','ax_slidingwindow_ANOVA_omega', ...
%      'data_axes', 1, 2, 3, 1, 2, 3, ...
%      'varargin_axes', {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 1'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', 'Monkey 2'}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1, 'title', ''}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      {'plottype', 'shade', ...
%      'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
%      'ABC_axes', 'ABACDB', 'nx', 2, 'ny', 3, ...
%      'varargin_fig', 'is_title', 'all');
