looper = S_looper_folder('../Data/');
jobs = S_jobs();
jobs.set_loopers({'folder'}, {looper});
jobs.power_off;
factornames = {'drop', 'delay', 'choice'};
model = [1,0,0;0,1,0;1,1,0; 0,0,1];
jobs.add_jobs_with_looper_folder([], 'W.anovan_slidingwindow', ...
    {'EPOCH_final_75_750', 'GAMES_final'}, {factornames, 'model', model}, {'anova_1window'});
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells', ...
    {'anova_1window'}, {}, 'anova_1window_allcells');
%%
jobs.power_on;
jobs.add_jobs_with_looper_folder([], 'W.select_cells', ...
    {'EPOCH_final', 'anova_1window'}, {}, 'EPOCH_sigcells', ...
    'inputfunc', @(args, cells, anv){cells, anv.info_cells.perc_significant});
jobs.add_jobs_with_looper_folder([], 'W.select_cells', ...
    {'EPOCH_final_go', 'anova_1window'}, {}, 'EPOCH_sigcells_go', ...
    'inputfunc', @(args, cells, anv){cells, anv.info_cells.perc_significant});
jobs.power_off;
jobs.add_jobs_with_looper_folder([], 'W.select_cells', ...
    {'EPOCH_final', 'anova_1window'}, {}, 'EPOCH_nonsigcells', ...
    'inputfunc', @(args, cells, anv){cells, ~anv.info_cells.perc_significant});
%%
jobs.power_on;
infiles = {'EPOCH_final_shuffled', 'EPOCH_final_shuffled_rate', 'EPOCH_final_shuffled_trial', ...
    'EPOCH_final_non0'};
outfiles = {'EPOCH_sigcells_shuffled', ...
    'EPOCH_sigcells_shuffled_rate', 'EPOCH_sigcells_shuffled_trial', ...
    'EPOCH_sigcells_final_non0'};
for i = 1:length(infiles)
    jobs.add_jobs_with_looper_folder([], 'W.select_cells', ...
        {infiles{i}, 'anova_1window'}, {}, outfiles{i}, ...
        'inputfunc', @(args, cells, anv){cells, anv.info_cells.perc_significant});
end
%%
jobs.power_on;
infiles = {'EPOCH_sigcells', 'EPOCH_nonsigcells', 'EPOCH_sigcells_shuffled', ...
    'EPOCH_sigcells_shuffled_rate', 'EPOCH_sigcells_shuffled_trial', ...
    'EPOCH_sigcells_final_non0', 'EPOCH_sigcells_go'};
for i = 1:length(infiles)
    jobs.add_jobs_with_looper_folder({'all', 'all'}, 'W.format_combinecells_and_games', ...
        {infiles{i}, 'GAMES_value'}, {}, W.file_suffix(infiles{i}, 'all'));
end

jobs.parfor_on;
jobs.overwrite_on;
jobs.run()
%%
% anova = W.load('../Data/anova_1window_allcells');
% info = anova.info_cells;
% W.writetable(info, '../Results/info_ANOVA.csv');
