%%
plt = SW_plt_from_yml('fig.yml');
plt.plt_switch.addABCs = false;
looper = S_looper_folder('../Data', '');
jobs = S_jobs();
jobs.set_loopers({'folder'}, {looper});
jobs.plotmode_on(plt);
jobs.power_off;
% jobs.add_jobs_with_looper_folder({'all', 'all'}, 'obj.plt_slidingwindow_ANOVA', ...
%     {'anova_nochocie_allcells'}, ...
%     {'legloc', 'SE', 'xlim', [-500, 1000], 'ylim', [0 0.7], ...
%         'plottype', 'shade'}, ...
%     {'anova_nochocie'});

jobs.add_jobs_with_looper_folder({'all', 'all'}, 'SW_fig', ...
    {'anova_choice_allcells'}, ...
    {'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 1, ...
     'varargin_axes', {'plottype', 'shade', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1}, ...
        {'plottype', 'shade', ...
            'legloc', 'NE', 'xlim', [-500, 1000], 'ylim', [-0.001 0.035], 'ytick', [-0.05:0.01:0.05]}, ...
     'ABC_axes', 'CD'}, ...
    {'anova_choice'});

jobs.power_on;
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'SW_fig', ...
    {'anova_choice_allcells', 'anova_choice_allcells_nonsig', 'anova_choice_shuffled_trial_allcells',...
    'anova_choice_shuffled_allcells', 'anova_choice_non0_allcells', 'anova_choice_shuffled_rate_allcells'}, ...
    {'axes', 'ax_slidingwindow_ANOVA', 'ax_slidingwindow_ANOVA', 'ax_slidingwindow_ANOVA', ...
    'ax_slidingwindow_ANOVA', 'ax_slidingwindow_ANOVA', 'ax_slidingwindow_ANOVA' ...
     'data_axes', 1, 2, 3, 4, 5, 6, ...
     'varargin_axes', {'plottype', 'shade', 'title', 'data', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1}, ...
        {'plottype', 'shade', 'title', 'non-sig cells', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1}, ...
        {'plottype', 'shade', 'title', 'shuffled, trial', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1}, ...
        {'plottype', 'shade', 'title', 'shuffled, time', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1}, ...
        {'plottype', 'shade', 'title', 'data, non-0', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1}, ...
        {'plottype', 'shade', 'title', 'shuffled, rate', ...
     'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.02 0.7], 'ytick', -1:.2:1}, ...
     'ABC_axes', 'ABCDE', 'nx', 2, 'ny', 3, 'varargin_fig', {'matrix_hole', [1 1 1; 1 1 1], 'is_title', 'all'}}, ...
    {'anova_shuffle'});
% jobs.add_jobs_with_looper_folder({'all', 'all'}, 'obj.plt_slidingwindow_ANOVA_omega', ...
%     {'anova_nochocie_allcells'}, ...
%     {'legloc', 'SE', 'xlim', [-500, 1000], 'ylim', [-0.005 0.04], ...
%         'plottype', 'shade'}, ...
%     {'anova_nochocie_omega'});
% jobs.add_jobs_with_looper_folder({'all', 'all'}, 'obj.plt_slidingwindow_ANOVA', ...
%     {'anova_value_cont_allcells'}, ...
%     {'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [0 0.7], ...
%         'plottype', 'shade'}, ...
%     {'anova_value_cont'});
% jobs.add_jobs_with_looper_folder({'all', 'all'}, 'obj.plt_slidingwindow_ANOVA_omega', ...
%     {'anova_value_cont_allcells'}, ...
%     {'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.005 0.04], ...
%         'plottype', 'shade'}, ...
%     {'anova_value_cont_omega'});
% jobs.add_jobs_with_looper_folder({'all', 'all'}, 'obj.plt_slidingwindow_ANOVA', ...
%     {'anova_value_allcells'}, ...
%     {'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [0 0.7], ...
%         'plottype', 'shade'}, ...
%     {'anova_value'});
% jobs.add_jobs_with_looper_folder({'all', 'all'}, 'obj.plt_slidingwindow_ANOVA_omega', ...
%     {'anova_value_allcells'}, ...
%     {'legloc', 'NW', 'xlim', [-500, 1000], 'ylim', [-0.005 0.04], ...
%         'plottype', 'shade'}, ...
%     {'anova_value_omega'});

% jobs.add_jobs_with_looper_folder({'all', 'all'}, 'obj.model_comparison', ...
%     {'result_RL'}, {}, ...
%     {'RL_comparison'});
% 
jobs.power_off;
jobs.add_jobs_with_looper_folder({'all', 'all'}, 'SW_fig', ...
    {'anova_go_allcells_formatted'}, ...
    {'axes', 'ax_slidingwindow_ANOVA','ax_slidingwindow_ANOVA_omega', ...
     'data_axes', 1, 1, ...
     'varargin_axes', {'plottype', 'shade', 'color', {'AZcactus', 'AZsky', 'AZsand', 'magenta'}, ...
     'legloc', 'W', 'xlim', [-500, 1000], 'ylim', [-0.03 0.6]}, ...
      {'plottype', 'shade', 'color', {'AZcactus', 'AZsky', 'AZsand', 'magenta'}, ...
      'legloc', 'W', 'xlim', [-500, 1000], 'ylim', [-0.001 0.02]}, ...
     'ABC_axes', 'AB'}, ...
    {'anova_go'});

jobs.parfor_off;
jobs.overwrite_on;
jobs.run()
%%
data = looper.looper_loadmix('games');
ids = {contains(looper.folders_names, 'S'), contains(looper.folders_names, 'T')};
xfit = {[],[]};
for i = 1:2
    W.print('fit animal %d', i);
    td = data{1}(ids{i});
    tab = vertcat(td{:});
    xfit{i} = function_model(tab, 1);
end
W.save('../Data/xfit_ITC.mat', 'xfit', xfit);
%%
xfit = W.load('../Data/xfit_ITC.mat');
games = {};
for i = 1:2
    W.print('test animal %d', i);
    td = data{1}(ids{i});
    tab = vertcat(td{:});
    games{i} = function_value(tab, xfit{i}, 'model_base');
end
%%
plt.figure(1,2)
xlms = {[0 2], [0 4]};
for i = 1:2
    plt.ax(3-i);
    params = xfit{i}.model_base.params_table;
    cc = W.cond_average_tab(games{i}, {'condition'}, {'choice','DV','drop', 'delay'});
    sp = 'ooosssddd';
    col = 'brgbrgbrg';
    xs = 0:0.01:5;
    cp = arrayfun(@(x)1./(1 + exp(-params.beta * x - params.thres)), xs);
    plt.plot(xs, cp * 100, [], 'line', 'color', 'black', 'LineWidth', 1);
    for j = 1:9
        plt.scatter(cc.avDV(j), cc.avCHOICE(j) * 100, [], 'shape', sp(j), ...
            'dotsize', 7, 'color', col(j));
    end
    plt.setfig_ax('ylabel', 'Accept Rate (%)', 'xlabel', '', 'ylim', [0 100], ...
        'ytick', [0:10:100], 'title', ['Monkey ' num2str(3-i)], 'xlim', xlms{i});
end
plt.update('behavior');